### ISSUE TITLE
allow 2 different optimizers to be customized from yaml

### ISSUE THREAD

**Issue by takumihoriba** [takumihoriba/WatChMaL#1]
YAML file should be able to specify optimizer configurations for training of both adversary(r) and main (f)

Tasks
- create logic to parse yaml for optimizers
- make sure they are initialized/instantiated correctly

Testing
- model training should run correctly
- add print statement for instantiation of optimizers; make sure indep optimizers were successfully instantiated

**Comment by takumihoriba** [comment]
Validation by print statements
- different optimizers being instantiated

```
OPTIMIZER:  Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    lr: 0.01
    maximize: False
    weight_decay: 0
)
OPTIMIZER ADV:  Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    lr: 0.005
    maximize: False
    weight_decay: 0
)
```

**Comment by takumihoriba** [comment]
New yaml file should look like this
```yaml
optimizers:
      label_predictor:
        _target_: torch.optim.Adam
        lr: 0.01
        weight_decay: 0
      domain_classifier:
        _target_: torch.optim.Adam
        lr: 0.005
        weight_decay: 0
```
